FROM centos:6.7

RUN yum -y install epel-release
RUN yum -y install R R-devel R-core

ADD ./rclient /clientdir

RUN cp /clientdir/librcall.so /usr/lib64

ENV R_HOME /usr/lib64/R

EXPOSE 8080
WORKDIR /clientdir

CMD ["./client"]
